###################################################
# Infrastructure Heat Template
#
# --Notes--
# The domain controller is given a static IP of 172.31.0.5.  The
# reason being is that I needed to set it as the DNS server for the
# management subnet.  If I try to do the IP dynamically, it results
# in a circular dependancy problem for creating the management subnet.
###################################################
heat_template_version: 2013-05-23
description:  VM Build Template

parameters:
  flavor:
    type: string
    
  image:
    type: string
    
  name:
    type: string
    
  ip_local:
    type: string
    default: ""

  nw_local:
    type: string

  ip_mgt:
    type: string
    default: ""

  nw_mgt:
    type: string

  user_data:
    type: string

  security_groups:
    type: string
    default: default

resources:
#####################################################
# Create Instances
###################################################
  server:
    type: OS::Nova::Server
    properties:
      flavor: { get_param: flavor }
      name: { get_param: name}
      config_drive: 'true'
      key_name: devops
      image: { get_param: image}
      networks: [{"fixed_ip": { get_param: ip_local}, "network": { get_param: nw_local}}, {"fixed_ip": { get_param: ip_mgt}, "network": { get_param: nw_mgt}}]
      user_data_format: RAW
      user_data: {get_param: user_data}
      security_groups: [ {get_param: security_groups}]