###################################################
# Infrastructure Heat Template
#
# --Notes--
# The domain controller is given a static IP of 172.31.0.5.  The
# reason being is that I needed to set it as the DNS server for the
# management subnet.  If I try to do the IP dynamically, it results
# in a circular dependancy problem for creating the management subnet.
###################################################
heat_template_version: 2013-05-23
description: <enter description here>

resources:
#####################################################
# Create Instances
# 1. Replace all values #xxx# with correct values
###################################################
  #vm#:
    type: build-2nic-vm.yaml
    properties:
      name: '#servername#'
      flavor: '#flavor#'
      image: '#image#'
# ip_local is only needed for static local IP
#     ip_local: 10.0.0.100
      nw_local: '#local network name#'
      nw_mgt: '#management network name#'
# ip_mgt is only needed for static management IP
#     ip_mgt: '62.193.13.171'
      user_data:
          get_file: scripts/#scriptname# 
# if you need to pass variables to a script replace user data lines above with commented out ones below.
#     user_data:
#       str_replace:
#           template:
#             get_file: scripts/#scriptname#    
#           params:
#             $var1: "#var1 value#"  
      security_groups: '#security group name#'