#########################################################
# VM Heat Template
# Command to Run
# heat stack-create -f .\server_template.yml <stackname>
# --Notes--
# To create a new template start with server_template.yml
#########################################################
heat_template_version: 2013-05-23
description: Private SQL DB Template

resources:
#####################################################
# Create Instances
###################################################
  sql01:
    type: build-2nic-vm.yaml
    properties:
      name: 'DEV-DB-01'
      flavor: 'm1.medium'
      image: 'Server2012R2'
      ip_local: 10.0.0.100
      nw_local: 'DEV_INTERNAL_SECURE'
      nw_mgt: 'DEV_EXT-MGMT_NET'
      ip_mgt: '62.193.13.171'
      user_data:
          get_file: scripts/install_sql.ps1 